name: anti_uav
channels:
  - defaults
dependencies:
  - ca-certificates=2025.12.2=hca03da5_0
  - libcxx=21.1.8=hb4ce287_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - pip=24.2=py38hca03da5_0
  - python=3.8.20=hb885b13_0
  - readline=8.3=h0b18652_0
  - setuptools=75.1.0=py38hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.44.0=py38hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - accessible-pygments==0.0.4
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.5.2
      - appnope==0.1.4
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.18.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - certifi==2026.1.4
      - cffi==1.17.1
      - cfgv==3.4.0
      - click==8.1.8
      - commonmark==0.9.1
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.5
      - cycler==0.12.1
      - datasets==3.1.0
      - decorator==5.2.1
      - dill==0.3.8
      - distlib==0.4.0
      - docutils==0.19
      - easydict==1.13
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - eval-type-backport==0.3.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - expecttest==0.3.0
      - fastapi==0.124.4
      - ffmpy==0.5.0
      - filelock==3.16.1
      - flake8==7.1.2
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.48.0
      - google-auth-oauthlib==1.0.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.70.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - identify==2.6.1
      - idna==3.11
      - imageio==2.35.1
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - isort==5.13.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - jittor==1.3.10.0
      - jmespath==0.10.0
      - jsonplus==0.8.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - myst-parser==3.0.1
      - networkx==3.1
      - nodeenv==1.10.0
      - numpy==1.24.4
      - oauthlib==3.3.1
      - opencv-python==4.13.0.92
      - opencv-python-headless==4.13.0.92
      - orjson==3.10.15
      - oss2==2.19.1
      - packaging==26.0
      - pandas==2.0.3
      - parso==0.8.6
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pre-commit==3.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - protobuf==5.29.6
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydata-sphinx-theme==0.14.4
      - pydub==0.25.1
      - pyflakes==3.2.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - recommonmark==0.7.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.3.3
      - rsa==4.9.1
      - ruff==0.15.2
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sphinx==6.2.1
      - sphinx-book-theme==1.0.1
      - sphinx-copybutton==0.5.2
      - sphinx-markdown-tables==0.0.17
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.3
      - starlette==0.44.0
      - sympy==1.13.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - tifffile==2023.7.10
      - timm==1.0.24
      - tomlkit==0.12.0
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.3
      - traitlets==5.14.3
      - typer==0.20.1
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - ultralytics==8.3.75
      - ultralytics-thop==2.0.18
      - urllib3==2.2.3
      - uvicorn==0.33.0
      - virtualenv==20.38.0
      - wcwidth==0.6.0
      - websockets==12.0
      - werkzeug==3.0.6
      - xxhash==3.6.0
      - yapf==0.30.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /opt/anaconda3/envs/anti_uav
